nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: []
    allow_headers: []
    allow_methods: []
    expose_headers: []
    max_age: 0
    hosts: []
    origin_regex: false
    forced_allow_origin_value: ~
  paths:
    '^/':
      allow_origin: ['*']
      allow_headers: ['*']
      allow_methods: ['POST', 'GET']
      max_age: 3600
